### ISSUE TITLE
Maybe the documentation is missing

### ISSUE THREAD

**Issue by vhext** [Theaninova/vite-plugin-kaitai#1]
1. I tried to use this plugin in my Vue3 project as per the documentation and got the error: missing module `kaitai-struct-compiler` and `yaml`

2. Fixed then after npm install ..., but i got vite.config.ts intellicense error: missing option parameter

> My vite.config.ts file
```ts
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { kaitai } from 'vite-plugin-kaitai'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    kaitai(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})


```

**Comment by Theaninova** [comment]
Hmm, it's been a hot minute since I made or used this
1. Described in [README.md#Installation](https://github.com/Theaninova/vite-plugin-kaitai#installation)
2. Not sure what that means, feel free though to look at what I did https://github.com/Theaninova/Maximumtune.org/blob/master/vite.config.js

**Comment by vhext** [comment]
Additional information on question 2:
```
Expected 1 arguments, but got 0.ts(2554)
index.d.ts(7, 32): An argument for 'options' was not provided.
(alias) kaitai(options: Partial<{
    generatedTypesFolder: string;
}>): Plugin<any>
import kaitai

```

```
[{
	"resource": "xxx/vite.config.ts",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 0.",
	"source": "ts",
	"startLineNumber": 11,
	"startColumn": 5,
	"endLineNumber": 11,
	"endColumn": 13,
	"relatedInformation": [
		{
			"startLineNumber": 7,
			"startColumn": 32,
			"endLineNumber": 7,
			"endColumn": 71,
			"message": "An argument for 'options' was not provided.",
			"resource": "xxx/node_modules/vite-plugin-kaitai/lib/index.d.ts"
		}
	]
}]
```

In vite-plugin-kaitai\lib\index.d.ts
```
export declare function kaitai(options: Partial<typeof defaultOptions>): Plugin;
```

May be `[options](options: Partial<typeof defaultOptions>)`  param is optional

PS: My english is not good, so some comment look weird, sorry

**Comment by Theaninova** [comment]
Seems like I forgot to mark the options as optional, I just pushed a new version that should fix it.

**Comment by vhext** [comment]
v1.0.2 it's work👍
