### ISSUE TITLE
[Feature Request]: Add Byte arrays type annotations support

### ISSUE THREAD

**Issue by vhexl** [Theaninova/vite-plugin-kaitai#3]
For Byte arrays type in `*.ksy.d.ts` type annotations is `unknown`

In [https://doc.kaitai.io/user_guide.html#_basic_data_types](https://doc.kaitai.io/user_guide.html#_basic_data_types) has: 

> Byte arrays are defined in the attribute syntax when you don’t specify anything as type. The size of a byte array is thus determined using size, size-eos or terminator, one of which is mandatory in this case. 

https://github.com/Theaninova/vite-plugin-kaitai/blob/b204b8f3b694698c8a4d55d10297ea46af1f5a40/src/kaitai-type-generator.ts#L86-L90

maybe we can

```diff
            ? convertExternalType(attribute.type)
            : typeof attribute.type === "object"
                ? [...new Set(Object.values(attribute.type.cases).map(it => convertExternalType(it)))].join(" | ")
+                : typeof attribute.size === "number" || (attribute.size_eos ?? false)
+                    ? "Uint8Array"
                    : "unknown";
    return attribute.repeat
```

**Comment by Theaninova** [comment]
Looks fine to me, feel free to open a pr!
